In [1]:
import numpy as np
import tensorflow as tf
sess=tf.Session()

C:\Users\AkhouriAditya\Anaconda2\envs\py36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
LSTM_CELL_SIZE = 4  # output size (dimension), which is same as hidden size in the cell

lstm_cell = tf.contrib.rnn.BasicLSTMCell(LSTM_CELL_SIZE, state_is_tuple=True)
state = (tf.zeros([2,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor 'zeros:0' shape=(2, 4) dtype=float32>,
 <tf.Tensor 'zeros:0' shape=(2, 4) dtype=float32>)

In [5]:
sample_inp = tf.constant([[1,2,3,4,3,2],[3,2,2,2,2,2]],dtype=tf.float32)
print(sess.run(sample_inp))

[[1. 2. 3. 4. 3. 2.]
 [3. 2. 2. 2. 2. 2.]]


In [7]:
with tf.variable_scope('lstm_sample'):
    output,state_new=lstm_cell(sample_inp,state)
sess.run(tf.global_variables_initializer())
print(sess.run(output))
print(sess.run(state_new))

[[-0.2942368  -0.2419689  -0.07741059  0.6640707 ]
 [-0.03015879 -0.3559764  -0.1198595   0.3626583 ]]
LSTMStateTuple(c=array([[-0.49986035, -0.55222404, -0.6384523 ,  0.8846347 ],
       [-0.05463266, -0.66045123, -0.6263808 ,  0.6568781 ]],
      dtype=float32), h=array([[-0.2942368 , -0.2419689 , -0.07741059,  0.6640707 ],
       [-0.03015879, -0.3559764 , -0.1198595 ,  0.3626583 ]],
      dtype=float32))


In [9]:
LSTM_CELL_SIZE = 4  #4 hidden nodes = state_dim = the output_dim 
input_dim = 6
num_layers = 2

In [11]:
cells=[]
for _ in range(num_layers):
    cell = tf.contrib.rnn.LSTMCell(LSTM_CELL_SIZE)
    cells.append(cell)
stacked_lstm=tf.contrib.rnn.MultiRNNCell(cells)

In [17]:
data=tf.placeholder(tf.float32,[None,None,input_dim])
output,state=tf.nn.dynamic_rnn(cell,data,dtype=tf.float32)

In [18]:
#input sequence length is 3, and the dimensionality of the inputs is 6.
#The input should be a Tensor of shape: [batch_size, max_time, dimension], in our case it would be (2, 3, 6)
#Batch size x time steps x features.
sample_input = [[[1,2,3,4,3,2],[1,2,1,1,1,2],[1,2,2,2,2,2]],[[1,2,3,4,3,2],[3,2,2,1,1,2],[0,0,0,0,3,2]]]
sample_input

[[[1, 2, 3, 4, 3, 2], [1, 2, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2]],
 [[1, 2, 3, 4, 3, 2], [3, 2, 2, 1, 1, 2], [0, 0, 0, 0, 3, 2]]]

In [21]:
sess.run(tf.global_variables_initializer())
sess.run(output,feed_dict={data:sample_input})

array([[[-0.01026246,  0.03243307,  0.0674006 , -0.27015474],
        [-0.18756633,  0.09216511,  0.22321768, -0.26076153],
        [-0.19298032,  0.11102337,  0.30076635, -0.31592256]],

       [[-0.01026246,  0.03243307,  0.0674006 , -0.27015474],
        [-0.21478483, -0.00843339,  0.32131952, -0.33091554],
        [-0.08279471,  0.22134057,  0.234205  ,  0.20588288]]],
      dtype=float32)

In [22]:
sess.run(state, feed_dict={data:sample_input})

LSTMStateTuple(c=array([[-0.32989222,  0.20382322,  0.38626155, -0.4145251 ],
       [-0.09593959,  0.25959614,  0.27071953,  0.23922989]],
      dtype=float32), h=array([[-0.19298032,  0.11102337,  0.30076635, -0.31592256],
       [-0.08279471,  0.22134057,  0.234205  ,  0.20588288]],
      dtype=float32))